# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/XRD-Parser/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" ;
	:requires
		"Carp 0",
		"Data::UUID 0",
		"Digest::SHA1 0",
		"Encode 0",
		"HTTP::Link::Parser 0.102",
		"LWP::UserAgent 0",
		"Object::AUTHORITY 0",
		"RDF::Trine 0.135",
		"Scalar::Util 0",
		"URI::Escape 0",
		"URI::URL",
		"XML::LibXML 1.70".

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/XRD/Parser.pm" .

